# @package _global_

defaults:
  - override /cluster: local
  - override /batching: regular

dataset:
  data_path: /ssd/Code/fairchem-esen/data/dipole

runner:
  max_epochs: 2
  evaluate_every_n_epochs: 1

batch_size: 2

job:
  logs_dir: /ssd/Code/fairchem-esen/logs
  logger:
    wandb_dir: /ssd/Code/fairchem-esen/wandb
  debug: True
  run_dir: /ssd/Code/fairchem-esen/checkpoint/run_dir # ${cluster.run_dir}