snapshot_dir: custom_dataset_root

custom_train:
  splits:
    train:
      src: ${dataset.data_path}/train/qm7_dipole_train.lmdb
      first_n: null  # Set to limit number of samples (e.g., 100)
  format: lmdb
  transforms:
    common_transform:
      dataset_name: custom

custom_val:
  splits:
    val:
      src: ${dataset.data_path}/val/qm7_dipole_validation.lmdb
  format: lmdb
  transforms:
    common_transform:
      dataset_name: custom

