snapshot_dir: custom_dataset_root

custom_train:
  splits:
    train:
      src: ${dataset.data_path}/qm7_train.lmdb
  format: lmdb
  transforms:
    common_transform:
      dataset_name: custom

custom_val:
  splits:
    val:
      src: ${dataset.data_path}/qm7_validation.lmdb
  format: lmdb
  transforms:
    common_transform:
      dataset_name: custom

